import { contentType } from '@optimizely/cms-sdk'

export const OT_CarouselSlide = contentType({
  key:         'OT_CarouselSlide',
  displayName: 'Carousel Slide',
  description: 'Single slide with image, headline, optional body copy, and CTA.',
  baseType:    '_component',
  // No compositionBehaviors — only exists as an array item inside OT_CarouselBlock
  properties: {
    image: {
      type:         'contentReference',
      displayName:  'Image',
      description:  'Background or featured image for this slide.',
      allowedTypes: ['_image'],
      group:        'OT_Content',
      sortOrder:    10,
    },
    imageAlt: {
      type:        'string',
      displayName: 'Image Alt Text',
      description: 'Descriptive alt text for screen readers.',
      isLocalized: true,
      maxLength:   150,
      group:       'OT_Content',
      sortOrder:   20,
    },
    eyebrow: {
      type:        'string',
      displayName: 'Eyebrow',
      description: 'Short label above the heading. Keep under 40 characters.',
      isLocalized: true,
      maxLength:   40,
      group:       'OT_Content',
      sortOrder:   30,
      indexingType: 'searchable',
    },
    heading: {
      type:        'string',
      displayName: 'Heading',
      description: 'Primary headline for this slide.',
      isLocalized: true,
      maxLength:   100,
      group:       'OT_Content',
      sortOrder:   40,
      indexingType: 'searchable',
    },
    body: {
      type:        'string',
      displayName: 'Body',
      description: 'Optional short body copy. Keep to 2–3 sentences.',
      isLocalized: true,
      maxLength:   300,
      group:       'OT_Content',
      sortOrder:   50,
      indexingType: 'searchable',
    },
    ctaLabel: {
      type:        'string',
      displayName: 'CTA Label',
      description: 'Button label. Requires CTA URL.',
      isLocalized: true,
      maxLength:   40,
      group:       'OT_Content',
      sortOrder:   60,
    },
    ctaUrl: {
      type:        'url',
      displayName: 'CTA URL',
      description: 'Destination for the CTA button.',
      isLocalized: true,
      group:       'OT_Content',
      sortOrder:   70,
    },
  },
})
