import { contentType } from '@optimizely/cms-sdk'

export const OT_TopicHubBucket = contentType({
  key:         'OT_TopicHubBucket',
  displayName: 'Topic Hub Content Bucket',
  description: 'A result section in the Topic Hub — defines what content type to surface and how to label the section.',
  baseType:    '_component',
  properties: {
    sectionHeadline: {
      type:        'string',
      isLocalized: true,
      maxLength:   80,
      displayName: 'Section Headline',
      description: 'Label shown above the result cards, e.g. "Events & Training"',
      group:       'OT_Content',
      sortOrder:   10,
    },
    sectionIcon: {
      type:        'string',
      format:      'selectOne',
      displayName: 'Section Icon',
      description: 'Icon displayed next to the section headline.',
      group:       'OT_Content',
      sortOrder:   20,
      enum: [
        { value: 'CalendarDays',  displayName: 'Calendar — Events / Training' },
        { value: 'Newspaper',     displayName: 'Newspaper — News / Blogs' },
        { value: 'FileText',      displayName: 'Document — Pages / Files' },
        { value: 'BookOpen',      displayName: 'Book — Resources / Library' },
        { value: 'Users',         displayName: 'People — Team / Practitioners' },
        { value: 'MapPin',        displayName: 'Pin — Locations / Places' },
        { value: 'Building2',     displayName: 'Building — Organizations' },
        { value: 'Video',         displayName: 'Video — Webinars / Media' },
        { value: 'Globe',         displayName: 'Globe — Web / Experiences' },
        { value: 'Award',         displayName: 'Award — Certifications / Recognition' },
        { value: 'Layers',        displayName: 'Layers — All Content' },
        { value: 'Sparkles',      displayName: 'Sparkles — AI / Featured' },
        { value: 'GraduationCap', displayName: 'Graduation — Education / Courses' },
        { value: 'Heart',         displayName: 'Heart — Health / Wellness' },
        { value: 'Scale',         displayName: 'Scale — Legal / Compliance' },
        { value: 'BarChart3',     displayName: 'Chart — Analytics / Data' },
        { value: 'Lightbulb',     displayName: 'Lightbulb — Insights / Ideas' },
        { value: 'Folder',        displayName: 'Folder — Files / Collections' },
        { value: 'Tag',           displayName: 'Tag — Categories / Labels' },
        { value: 'MessageSquare', displayName: 'Chat — Community / Discussion' },
      ],
    },
    sectionContentType: {
      type:        'string',
      format:      'selectOne',
      displayName: 'Content Type',
      description: 'The type of content surfaced in this section.',
      group:       'OT_Content',
      sortOrder:   30,
      enum: [
        { value: 'blogs',          displayName: 'News & Research (Blogs)' },
        { value: 'events',         displayName: 'Events & Training' },
        { value: 'assets',         displayName: 'Documents (DAM Assets)' },
        { value: 'experiences',    displayName: 'Pages & Experiences' },
        { value: 'locations',      displayName: 'Locations' },
        { value: 'practitioners',  displayName: 'Practitioners / Team Members' },
      ],
    },
  },
})
